# Generated by Django 5.2.14 on 2026-05-12 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("todos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="todos",
                to="todos.category",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="todos", to="todos.tag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("owner", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("owner", "slug")},
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["owner", "completed"], name="todos_todo_owner_i_f75edb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["owner", "priority"], name="todos_todo_owner_i_d44aab_idx"
            ),
        ),
    ]
